# Generated by Django 5.1.3 on 2024-11-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Farmer', 'Farmer'), ('Buyer', 'Buyer')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
