# Generated by Django 5.1.3 on 2024-11-23 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_farmrank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmrank',
            name='value',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
