# Generated by Django 5.1.3 on 2024-11-23 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_farmrank'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='farm_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_items', to='market.farm'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_name',
            field=models.CharField(choices=[('kg', 'kg'), ('pcs', 'pcs'), ('litres', 'litres')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
