# Generated by Django 5.1.3 on 2024-11-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_delivery_cost_remove_delivery_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='order',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
